# Generated by Django 4.2.11 on 2024-04-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giohang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_oder', models.DateTimeField(auto_now_add=True)),
                ('Complete', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=200, null=True)),
                ('Giatien', models.FloatField()),
                ('Diachi', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=200, null=True)),
                ('Giatien', models.FloatField()),
                ('Diachi', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Giohang_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(blank=True, default=0, null=True)),
                ('date_them', models.DateTimeField(auto_now_add=True)),
                ('giohang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trangchu.giohang')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trangchu.phong')),
            ],
        ),
    ]
