# Generated by Django 4.2.11 on 2024-04-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='Netflix',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
