# Generated by Django 4.2.11 on 2024-04-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0004_delete_khachhang_phong_bep_phong_bon_tam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phong',
            old_name='Bep',
            new_name='Beprieng',
        ),
        migrations.RenameField(
            model_name='phong',
            old_name='Bon_tam',
            new_name='Bontam',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='Giatien',
        ),
        migrations.AddField(
            model_name='phong',
            name='Gia14h_12h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='Gia1h_19h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='Gia20h_9h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='Gia4tieng',
            field=models.FloatField(null=True),
        ),
    ]
