# Generated by Django 4.2.11 on 2024-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0005_rename_bep_phong_beprieng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='Hinhanh',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
