# Generated by Django 4.2.11 on 2024-04-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0006_phong_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='Gia14h_12h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='Gia1h_19h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='Gia20h_9h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='Gia4tieng',
            field=models.IntegerField(null=True),
        ),
    ]
