# Generated by Django 4.2.11 on 2024-04-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0007_alter_phong_gia14h_12h_alter_phong_gia1h_19h_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phong',
            old_name='Gia1h_19h',
            new_name='Gia10h_19h',
        ),
    ]
