# Generated by Django 4.2.11 on 2024-04-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0008_rename_gia1h_19h_phong_gia10h_19h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang',
            name='Complete',
        ),
        migrations.RemoveField(
            model_name='giohang_items',
            name='date_them',
        ),
    ]
