# Generated by Django 4.2.11 on 2024-04-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0010_giohang_items_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phong',
            name='Gia10h_19h',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='Gia14h_12h',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='Gia20h_9h',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='Gia4tieng',
        ),
        migrations.CreateModel(
            name='Banggia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gia4tieng', models.IntegerField(blank=True, null=True)),
                ('Gia20h_9h', models.IntegerField(blank=True, null=True)),
                ('Gia10h_19h', models.IntegerField(blank=True, null=True)),
                ('Gia14h_12h', models.IntegerField(blank=True, null=True)),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trangchu.phong')),
            ],
        ),
    ]
